2021 07 removing customization parameters
agenius-logesh/DGEobj.plots pull request #6
Opened 2021-07-14 12:26 UTC by agenius-logesh

2021-07-15 12:07 UTC, saranya-ag requested changes
@agenius-logesh  - As discussed , can you let the plot take default values for size, shape and transparency. Only in cases, where a plot is being sized by or shaped by a attribute, hardcode the values. Colors can be hardcoded.

2021-07-15 12:07 UTC, saranya-ag commented on R/cdfPlot.R
>                      insetTitle     = NULL,
change to Viewport title

2021-07-15 12:07 UTC, saranya-ag commented on R/cdfPlot.R
> +            length(ylab) == 1)) {
alignment is wrong for this . revert it back to what it was.

2021-07-15 12:07 UTC, saranya-ag commented on R/cdfPlot.R
> +            length(ylab) == 1)) {
Length(ylab) comes within the all function. So it should not be the same level as all

2021-07-15 12:07 UTC, saranya-ag commented on R/comparePlot.R
> +#'                         title = "Plot Title"
You are missing a comma here.

2021-07-15 13:18 UTC, agenius-logesh commented on R/cdfPlot.R
>                      insetTitle     = NULL,
done

2021-07-15 13:18 UTC, agenius-logesh commented on R/cdfPlot.R
> +            length(ylab) == 1)) {
done

2021-07-15 13:20 UTC, agenius-logesh commented on R/comparePlot.R
> +#'                         title = "Plot Title"
done

2021-07-20 13:15 UTC, saranya-ag requested changes

2021-07-20 13:15 UTC, saranya-ag commented on R/cdfPlot.R
> +#' @param contrast A character vector of a topTable data in DGEobj and its a class of dataframe
Wrong definition - You are passing only one contrast

2021-07-20 13:15 UTC, saranya-ag commented on R/cdfPlot.R
> +#'    # Plot to console (DGEdata is a name of DGEonj and
DGEobj

2021-07-20 13:15 UTC, saranya-ag commented on R/cdfPlot.R
> +#'    contrast is a dataframe from DGEobj)
contrast is  the name of a top table from DGEobj

2021-07-20 13:15 UTC, saranya-ag commented on R/cdfPlot.R
> +                            msg = "DGEdata must be specified as class of DGEobj.")
DGEdata must be specified and must belong to class DGeobj

2021-07-20 13:15 UTC, saranya-ag commented on R/cdfPlot.R
> +                            msg = "contrast to be a singular value of class character and must be one from DGEdata with LogIntensity and LogRatio columns and optionally a p-value.")
"contrast to be a singular value of class character and must be one of the names of the top tables in DGEdata.

2021-07-20 13:15 UTC, saranya-ag commented on R/comparePlot.R
> +#' @param contrastOne and
There is only going to be a vector of contrast

2021-07-20 13:15 UTC, saranya-ag commented on R/comparePlot.R
> +#' @param contrastOne and
You need to update this

2021-07-20 13:15 UTC, saranya-ag commented on R/comparePlot.R
> +                        contrastOne,
Change this to one contrast

2021-07-20 13:15 UTC, saranya-ag commented on R/ggplotMDS.R
> +                                              dataPointSize           = 10,
Dont hardcode this value

2021-07-20 13:15 UTC, saranya-ag commented on R/ggplotMDS.R
>      intercept_flag   <- FALSE
You dont need a intercept_flag and length here i think -if you are not customizing colors

2021-07-20 13:15 UTC, saranya-ag commented on R/ggplotMDS.R
>      intercept_flag   <- FALSE
Can you check once more

2021-07-20 13:15 UTC, saranya-ag commented on R/ggplotMDS.R
> +                                              shapes                  = "circle",
Dont hard code this value

2021-07-20 13:15 UTC, saranya-ag commented on R/obsPlot.R
> +#' @param color Color for the boxplot or the violin ploy (default = "deepskyblue3")
Color was supposed to go away

2021-07-20 13:15 UTC, saranya-ag commented on R/obsPlot.R
> +                    color               = "deepskyblue3",
Color was supposed to go away.

2021-07-20 13:15 UTC, saranya-ag commented on R/obsPlot.R
> +    if (any(is.null(color),
remove color

2021-07-20 13:15 UTC, saranya-ag commented on R/plotDispersion.R
> +                                                 fitLineStyle            = "solid",
remove fitLineStyle

2021-07-20 13:15 UTC, saranya-ag commented on R/plotDispersion.R
> +                            linetype = "solid")
can you remove lineType

2021-07-20 13:15 UTC, saranya-ag commented on R/plotDispersion.R
> +            geom_point(shape = "circle",
can you remove shape

2021-07-20 15:24 UTC, agenius-logesh commented on R/obsPlot.R
> +    if (any(is.null(color),
its completed in another branch.

2021-07-20 15:24 UTC, agenius-logesh commented on R/obsPlot.R
> +                    color               = "deepskyblue3",
its completed in another branch.

2021-07-20 15:24 UTC, agenius-logesh commented on R/obsPlot.R
> +#' @param color Color for the boxplot or the violin ploy (default = "deepskyblue3")
its completed in another branch.

2021-07-20 15:25 UTC, agenius-logesh commented on R/comparePlot.R
> +                        contrastOne,
its completed in another branch.

2021-07-20 15:25 UTC, agenius-logesh commented on R/comparePlot.R
> +#' @param contrastOne and
its completed in another branch.

2021-07-20 15:26 UTC, agenius-logesh commented on R/cdfPlot.R
> +                            msg = "contrast to be a singular value of class character and must be one from DGEdata with LogIntensity and LogRatio columns and optionally a p-value.")
its completed in another branch.

2021-07-20 15:26 UTC, agenius-logesh commented on R/cdfPlot.R
> +                            msg = "DGEdata must be specified as class of DGEobj.")
its completed in another branch.

2021-07-20 15:26 UTC, agenius-logesh commented on R/cdfPlot.R
> +#'    contrast is a dataframe from DGEobj)
its completed in another branch.

2021-07-20 15:26 UTC, agenius-logesh commented on R/cdfPlot.R
> +#'    # Plot to console (DGEdata is a name of DGEonj and
its completed in another branch.

2021-07-20 15:26 UTC, agenius-logesh commented on R/cdfPlot.R
> +#' @param contrast A character vector of a topTable data in DGEobj and its a class of dataframe
its completed in another branch.

2021-07-20 15:27 UTC, agenius-logesh commented on R/ggplotMDS.R
> +                                              dataPointSize           = 10,
if we are not hard coding this the pointsize too large

2021-07-20 15:30 UTC, agenius-logesh commented on R/plotDispersion.R
> +                            linetype = "solid")
Its already completed.

2021-07-20 15:31 UTC, agenius-logesh commented on R/plotDispersion.R
> +                                                 fitLineStyle            = "solid",
Its already completed.

2021-07-21 16:41 UTC, merged